#!/bin/ksh

print =====================================================
print Dry-running rmtree on current dir as a simple test...
print =====================================================

rmtree -dS .
